### ISSUE TITLE
While playing the video it's a stuck fraction of seconds in the middle of playing.

### ISSUE THREAD

**Issue by karthickZenitus** [aws-samples/amazon-ivs-feed-ios-demo#13]
While playing the video it's a stuck fraction of seconds in the middle of playing. Can you please check this video?

https://user-images.githubusercontent.com/90257772/175881522-4ba42784-c8b4-44a4-b057-b3876b89e2e6.mp4

.

**Comment by slee-aws** [comment]
Hi @karthickZenitus are you referring to the loading spinner at 0:15 and 0:18? If so, this is because these video are live streams, so as you change streams, it takes your device a second to fetch the latest segments from the stream.

**Comment by karthickZenitus** [comment]
ya ok... will check it and then while playing the video, the device gets heat for a maximum of 15 to 20 minutes.

**Comment by mboulin** [comment]
Closing this issue for now, since the short pause when navigating between streams is expected in this demo.
Do note, this demo shows how you can build a scrollable feed of multiple video streams. When scrolling, playback will pause while it loads the new video stream. Live video streams differ from traditional video files. The sample streams used in this demo are for demonstration purposes only, and should be replaced with your own IVS streams.
